# Profitability Ratios

I've previously written about [Efficiency](https://www.linkedin.com/pulse/cash-king-calculating-conversion-cycles-determine-companys-jon-placa), [Liquidity](https://www.linkedin.com/pulse/liquidity-ratios-jon-placa), and [Solvency Ratios](https://www.linkedin.com/pulse/solvency-ratios-jon-placa) - in this posting we'll wrap up the fundamental ratio analysis by focusing on [Profitability Ratios](http://www.investopedia.com/terms/p/profitabilityratios.asp). 

Profitability ratios are classified as finanical metrics used to illustrate a company's capability to effectively generate revenue, hopefully outweighing the company's expenses. Unlike most Liquidity, Solvency, and Efficiency ratios that draw their data from the [Balance Sheet](http://www.investopedia.com/terms/b/balancesheet.asp), most Profitability ratios derive their information from the [Income Statement](http://www.investopedia.com/terms/i/incomestatement.asp?ad=dirN&qo=investopediaSiteSearch&qsrc=0&o=40186) (also know as the "Profit & Loss" or "P&L"). Additionally, most analysis compares year-over-year changes in Profitability Ratios to adjust for any [seasonality](http://www.investopedia.com/terms/s/seasonality.asp) associated with a particular business.

In this posting, we'll continue our trend of analyzing [Boeing's (BA)](https://finance.yahoo.com/quote/ba?ltr=1) annual financials with [Quandl's API](Quandl.com) supplying relevant information.

In [5]:
#Importing Quandl API
import quandl

#API Key Application
quandl.ApiConfig.api_key = '[API KEY]'
quandl.ApiConfig.api_version = '2015-04-09'

#Pull in Quandl data for BA (Boeing Co.)
data = quandl.get_table('ZACKS/FC', ticker='BA', per_type='A')
data.head(10)

,m_ticker,ticker,comp_name,comp_name_2,exchange,currency_code,per_end_date,per_type,per_code,per_fisc_year,...,stock_based_compsn_qd,cash_flow_oper_activity_qd,net_change_prop_plant_equip_qd,comm_stock_div_paid_qd,pref_stock_div_paid_qd,tot_comm_pref_stock_div_qd,wavg_shares_out,wavg_shares_out_diluted,eps_basic_net,eps_diluted_net
None,,,,,,,,,,,,,,,,,,,,,
0,BA,BA,BOEING CO,Boeing Company (The),NYSE,USD,2011-12-31,A,None,2011,...,None,None,None,None,None,None,744.1,750.6,5.39,5.34
1,BA,BA,BOEING CO,Boeing Company (The),NYSE,USD,2012-12-31,A,None,2012,...,None,None,None,None,None,None,755.7,761.5,5.15,5.11
2,BA,BA,BOEING CO,Boeing Company (The),NYSE,USD,2013-12-31,A,None,2013,...,None,None,None,None,None,None,758.9,767.6,6.03,5.96
3,BA,BA,BOEING CO,Boeing Company (The),NYSE,USD,2014-12-31,A,None,2014,...,None,None,None,None,None,None,727.6,736.7,7.47,7.38
4,BA,BA,BOEING CO,Boeing Company (The),NYSE,USD,2015-12-31,A,None,2015,...,None,None,None,None,None,None,686.9,695.0,7.52,7.44
5,BA,BA,BOEING CO,Boeing Company (The),NYSE,USD,2016-12-31,A,None,2016,...,None,None,None,None,None,None,635.5,642.8,7.70,7.61

## Profit Margin

Profit Margin is one of the most common metrics used when describing any company. The profit margin indicates how much money is earned through the sale of a good. However, there are different *types* of Profit Margins, most notably the "Gross Profit Margin", "Operating Profit Margin", and "Net Profit Margin". 

By analyzing each profit margin type, we can determine the distribution of expenses incurred when producing and selling an item.

### Gross Profit Margin

The Gross Profit Margin compares the "Cost of Goods (COGs)" (e.g materials, direct labor, etc.) associated with the sale of a specific product. Depending on the industry, COGs can make up a(n) (in)significant portion of the overall sales cost. For example, the manufacturing industry should expect a higher Cost of Goods value than an internet-based business because manufacturers have to account for material, direct labor, packaging, and freight costs. 

Gross Profit Margins are calculated as:

**Gross Profit Margin = (Revenue - COGS) / Revenue**

In [8]:
#Calculate Gross Margin
df = data[['per_fisc_year','tot_revnu','cost_good_sold']]
df['gross_profit'] = df.tot_revnu - df.cost_good_sold
df['gross_margin_pct'] = df.gross_profit/df.tot_revnu
df

/Users/home/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/home/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

      per_fisc_year  tot_revnu  cost_good_sold  gross_profit  gross_margin_pct
None
0              2011    68735.0         55739.0       12996.0          0.189074
1              2012    81698.0         68556.0       13142.0          0.160861
2              2013    86623.0         73193.0       13430.0          0.155040
3              2014    90762.0         76683.0       14079.0          0.155120
4              2015    96114.0         82024.0       14090.0          0.146597
5              2016    94571.0         80731.0       13840.0          0.146345

Notice how we've compared the year-over-year gross margin values to account for any seasonality. Through our analysis we can see a consistent decrease in gross margin over a 6-year period. The decrease in gross margin might be attributed to rising material/labor costs or a restructure of COGs recognition (i.e classifying a previous Operating Expense as a COG); further investigation is needed to clarify why the gross margin percentage has been decreasing.

### Operating Profit Margin

If we proceed down the Income Statement, after COGs we'd be presenting with Operating Expenses. [Operating Expenses](http://www.investopedia.com/terms/o/operating_expense.asp) are costs that are incurred during normal business activity; these expenses will be generated regardless whether or not a sale occurs. Examples of Operating Expenses include salaries, rent, utilities, etc.. The Operating Profit Margin, much like the Gross Margin, will illustrate how money money is earned on each sale of a product after COGs and Operating Expenses are accounted for.

**Operating Profit Margin = Operating Income / Revenue**

*where Operating Income = Gross Profit - Operating Expense
*where Gross Profit = Revenue - COGs*

In [9]:
df = data[['per_fisc_year','tot_revnu','cost_good_sold','gross_profit','tot_oper_exp','oper_income']]
df['op_profit_margin_pct'] = df.oper_income / df.tot_revnu
df

/Users/home/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

,per_fisc_year,tot_revnu,cost_good_sold,gross_profit,tot_oper_exp,oper_income,op_profit_margin_pct
None,,,,,,,
0,2011,68735.0,55739.0,12996.0,62912.0,5823.0,0.084717
1,2012,81698.0,68556.0,13142.0,75408.0,6290.0,0.076991
2,2013,86623.0,73193.0,13430.0,80061.0,6562.0,0.075754
3,2014,90762.0,76683.0,14079.0,83289.0,7473.0,0.082336
4,2015,96114.0,82024.0,14090.0,88671.0,7443.0,0.077439
5,2016,94571.0,80731.0,13840.0,88737.0,5834.0,0.061689

Similar to the Gross Margin, we see a consistent decrease in margins over a 6-year period. In terms of Operating Margin, the decrease in profitability is directly contributed to an increase in Operating Expenses. If we drill into the Operating Expenses, we can see where the increase in expenditures is occurring.

In [24]:
df = data[['per_fisc_year','int_exp_oper',
           'res_dev_exp',
           'tot_sell_gen_admin_exp',
           'other_oper_income_exp',
          'tot_oper_exp']]

df

,per_fisc_year,int_exp_oper,res_dev_exp,tot_sell_gen_admin_exp,other_oper_income_exp,tot_oper_exp
None,,,,,,
0,2011,149.0,3918.0,3408.0,302.0,62912.0
1,2012,109.0,3298.0,3717.0,272.0,75408.0
2,2013,75.0,3071.0,3956.0,234.0,80061.0
3,2014,69.0,3047.0,3767.0,277.0,83289.0
4,2015,64.0,3331.0,3525.0,273.0,88671.0
5,2016,59.0,4627.0,3616.0,296.0,88737.0

Drilling into Operating Expenses show from 2011 to 2014, the company increased spending in Selling, General, and Administrative departments while simultaneously decreasing Research & Design expenses. However, Boeing reversed this strategy in 2015 and 2016, opting to pursue R&D departments. 

Oddly enough, if we compare the 2011-2016 revenues, Boeing seemed more efficient in Operating Margins, despite providing the SG&A departments with less funding. It would be interesting to investigate the headcounts of these departments during these time periods to understand whether or not Boeing hired more, less efficient people (in the years where Operating Margin decreased), or maintained the same headcount but increased salaries for existing employees. Regardless, Boeing has seen a significant decrease in Operating Margin recently. 

*NOTE: [Boeing has annouced layoffs](http://money.cnn.com/2017/03/17/news/companies/boeing-signals-may-layoffs/) (~2,000 people; March 2017) in order to reduce costs and increase Operating Margins.*

### Net Profit Margin

Continuing our walk down the Income Statement, we can calculate our Net Profit Margin. The Net Profit Margin takes into account COGs, Operating Expenses, Interest, and Taxes (note, dividends are not accounted for in Net Profit Margin).

The Net Profit Margin is as follows:

**Net Profit Margin = (COGs + Operating Expense + Interest Expense + Tax) / Revenue**

*NOTE: The Quandl API takes COGs into account when calculating Operating Expenses (tot_oper_exp). I believe Quandl could improve their API by only including Operating Expenses in this category, but an argument can be had for either approach.*

In [11]:
df = data[['per_fisc_year',
           'tot_revnu',
           'cost_good_sold',
           'tot_oper_exp',
           'tot_non_oper_income_exp',
           'tot_provsn_income_tax',
           'income_cont_oper',
           'income_discont_oper',
           'consol_net_income_loss']]

df['net_margin_pct'] = df.consol_net_income_loss / df.tot_revnu
df

/Users/home/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,per_fisc_year,tot_revnu,cost_good_sold,tot_oper_exp,tot_non_oper_income_exp,tot_provsn_income_tax,income_cont_oper,income_discont_oper,consol_net_income_loss,net_margin_pct
None,,,,,,,,,,
0,2011,68735.0,55739.0,62912.0,-430.0,1382.0,4011.0,7.0,4018.0,0.058456
1,2012,81698.0,68556.0,75408.0,-380.0,2007.0,3903.0,-3.0,3900.0,0.047737
2,2013,86623.0,73193.0,80061.0,-330.0,1646.0,4586.0,-1.0,4585.0,0.052931
3,2014,90762.0,76683.0,83289.0,-336.0,1691.0,5446.0,NaN,5446.0,0.060003
4,2015,96114.0,82024.0,88671.0,-288.0,1979.0,5176.0,NaN,5176.0,0.053853
5,2016,94571.0,80731.0,88737.0,-266.0,673.0,4895.0,NaN,4895.0,0.051760

Finally, we can see Boeing's overall margin; for each dollar Boeing sells, the company collects ~$0.05. Despite Boeing's continously decreasing Gross Margin and Operating Margins, the company is able to maintain a Net Margin of 5%-6% year-over-year. Further investigation concludes that Boeing is able to pick up Net Margin percentage points by decreasing their tax liability (see: "Effective Tax Rate"):

# Effective Tax Rate

The effective Tax Rate indicates how much of a company's Pre-Tax Income is paid in taxes. For large companies, Effective Tax Rates can make/break annual earnings. Therefore, many companies pay great attention to any tax liabilities (and opportunities) that impact their businesses.

In our example below, we show that Boeing has been able to greatly reduce their Effective Tax Rate which has helped maintain steady Net Profit Margins (despite volatility in Gross & Operating Margins):

In [12]:
df = data[['per_fisc_year',
           'pre_tax_income',
           'tot_provsn_income_tax']]


df['effective_tax_rate'] = df.tot_provsn_income_tax / df.pre_tax_income
df

/Users/home/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

      per_fisc_year  pre_tax_income  tot_provsn_income_tax  effective_tax_rate
None
0              2011          5393.0                 1382.0            0.256258
1              2012          5910.0                 2007.0            0.339594
2              2013          6232.0                 1646.0            0.264121
3              2014          7137.0                 1691.0            0.236934
4              2015          7155.0                 1979.0            0.276590
5              2016          5568.0                  673.0            0.120869

# Returns

"Returns" equate to the capital gains/losses relative to an investment. Ideally, investors would like to see a positive return (gain) for each of their investments, but this cannot be gauranteed. None the less, despite the risk, investors are willing to allocate their capital to companies in hopes that the company will effectively use their new capital and generate a positive return - which is then paid back to the original investor. 

To understand which companies are most effective at deploying investor capital, Financial Analysts refer to the following ratios: "Return on Assets", "Return on Equity", and "Return on Capital Employed".

## Return on Assets

"Return on Aseets" (ROA) illustrates how effective a company is in deploying and profitiing from their assets. The ROA is calculated as follows:

**Return on Assets = Net Income / Avg Total Assets**

*where Avg Total Assets = (PY Assets + Current Year Assets) / 2*

In [10]:
df = data[['per_fisc_year',
           'consol_net_income_loss',
          'tot_asset',
          'curr_portion_debt',
          'tot_lterm_debt',
           'tot_share_holder_equity']]

#Calculate the average between Prior Year and Current Year
df['avg_tot_assets'] = df.tot_asset.rolling(window=2).mean() 

#Calculate Return on Assets (ROA)
df['ROA'] = df.consol_net_income_loss / df.avg_tot_assets

df

/Users/home/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/home/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,per_fisc_year,consol_net_income_loss,tot_asset,curr_portion_debt,tot_lterm_debt,tot_share_holder_equity,avg_tot_assets,ROA
None,,,,,,,,
0,2011,4018.0,79986.0,2353.0,10018.0,3608.0,NaN,NaN
1,2012,3900.0,88896.0,1436.0,8973.0,5967.0,84441.0,0.046186
2,2013,4585.0,92663.0,1563.0,8072.0,14997.0,90779.5,0.050507
3,2014,5446.0,92921.0,929.0,8141.0,8790.0,92792.0,0.058690
4,2015,5176.0,94408.0,1234.0,8730.0,6397.0,93664.5,0.055261
5,2016,4895.0,89997.0,384.0,9568.0,877.0,92202.5,0.053090

In a broad sense, Financial Analysts tend to prefer ROA > 5%. However, asset-light businesses (e.g Services, Internet-based businesses) tend to have a higher ROA. It is due to this skew that Financial Analysts must take the ROA with a grain-of-salt - each business must be investigated, compared to their peers, and viewed in a historical context.

## Return on Equity

Similar to ROA, "Return on Equity" (ROE), is the measurement of profitability for each shareholder's invested capital. 

However, ROE does have some noteworthy downsides and, as a result, must be taken in context with other indicators:

1) Shareholder's equity includes Preferred Stock, stock that may be elligible for dividends and thus, ROE may underestimate the overall gain/loss per shareholder. 

2) A company with that has a small Equity pool and that is primarily financed by debt may show a high ROE figure. 

**Return on Equity = Net Income / Avg Shareholder Equity**

In [12]:
df = data[['per_fisc_year',
           'consol_net_income_loss',
          'tot_asset',
          'curr_portion_debt',
          'tot_lterm_debt',
           'tot_share_holder_equity']]

#Calculate the average between Prior Year and Current Year
df['avg_share_holder_equity'] = df.tot_share_holder_equity.rolling(window=2).mean() 

#Calculate Return on Assets (ROA)
df['ROE'] = df.consol_net_income_loss / df.avg_share_holder_equity

df

/Users/home/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/home/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,per_fisc_year,consol_net_income_loss,tot_asset,curr_portion_debt,tot_lterm_debt,tot_share_holder_equity,avg_share_holder_equity,ROE
None,,,,,,,,
0,2011,4018.0,79986.0,2353.0,10018.0,3608.0,NaN,NaN
1,2012,3900.0,88896.0,1436.0,8973.0,5967.0,4787.5,0.814621
2,2013,4585.0,92663.0,1563.0,8072.0,14997.0,10482.0,0.437417
3,2014,5446.0,92921.0,929.0,8141.0,8790.0,11893.5,0.457897
4,2015,5176.0,94408.0,1234.0,8730.0,6397.0,7593.5,0.681636
5,2016,4895.0,89997.0,384.0,9568.0,877.0,3637.0,1.345889

Clearly, we can see the disadvantages with using ROE in an isolated state. As previously mentioned in our Solvency Ratio tutorial, [Boeing conducted a stock repurchase program in 2016](http://investors.boeing.com/investors/investor-news/press-release-details/2016/Boeing-Board-Raises-Dividend-Renews-Share-Repurchase-Authorization/default.aspx); as a result, our Return on Equity analysis for Fiscal Year 2016 may be unreliable.

## Return on Capital Employed

"Return on Capital Employed", or "ROCE", is a financial indicator that addresses issues associated with ROE (see: "Ruturn on Equity", noteworthy downsides #2). Return on Capital Employed rightfully takes into account a company's liabilities when calculating returns. As a result, companies that finance the majority of their business through debt (and not shareholder's equity) will have a lower ROCE value.

**Return on Capital Employed = EBIT / Capital Employed**

*where Capital Employed = Avg Debt Liabilities / Avg Shareholder's Equity*

In [18]:
df = data[['per_fisc_year',
           'ebit',
          'tot_asset',
          'curr_portion_debt',
          'tot_lterm_debt',
           'tot_share_holder_equity']]

df['tot_debt'] = df.curr_portion_debt + df.tot_lterm_debt

#Calculate the average between Prior Year and Current Year
df['avg_debt']= df.tot_debt.rolling(window=2).mean()
df['avg_share_holder_equity'] = df.tot_share_holder_equity.rolling(window=2).mean() 

df['capital_employed'] = df.avg_debt + df.avg_share_holder_equity

df['ROCE'] = df.ebit / df.capital_employed
df

/Users/home/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/home/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/home/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/home/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/home/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,per_fisc_year,ebit,tot_asset,curr_portion_debt,tot_lterm_debt,tot_share_holder_equity,tot_debt,avg_debt,avg_share_holder_equity,capital_employed,ROCE
None,,,,,,,,,,,
0,2011,5972.0,79986.0,2353.0,10018.0,3608.0,12371.0,NaN,NaN,NaN,NaN
1,2012,6399.0,88896.0,1436.0,8973.0,5967.0,10409.0,11390.0,4787.5,16177.5,0.395549
2,2013,6637.0,92663.0,1563.0,8072.0,14997.0,9635.0,10022.0,10482.0,20504.0,0.323693
3,2014,7542.0,92921.0,929.0,8141.0,8790.0,9070.0,9352.5,11893.5,21246.0,0.354984
4,2015,7507.0,94408.0,1234.0,8730.0,6397.0,9964.0,9517.0,7593.5,17110.5,0.438736
5,2016,5893.0,89997.0,384.0,9568.0,877.0,9952.0,9958.0,3637.0,13595.0,0.433468

Our ROCE calculation gives a much more realistic profitability ratio; when taking debt into account, Boeing's returns decrease to levels that reflect their recent borrowings. 

In general, a company's ROCE should match or exceed their current borrowing rates - failure to exceed borrowing rates implies that debt is being improperly managed and that the company is actually losing money for each dollar they borrow. Fortunately, in Boeing's case, they are properly utilizing their borrowings and increasing the business's value.

# Conclusion

Profitability ratios are great indicators in determining a company's overall performance. However, when analyzing profitability ratios, it's imperative to compare each ratio to a comparable timeframe (e.g prior year); accurate time-frame comparisons will help remove any seasonality that may exist within the business. Furthermore, analysts must be aware of obscure events that might impact profitability (e.g stock buybacks, new acquisitions, etc.) as certain events might skew/bias some calculations. 

To learn about other types of ratios that can be calculated to give a better picture of a business's financials/operations, please review my postings about [Liquidity](https://www.linkedin.com/pulse/liquidity-ratios-jon-placa), Solvency, and Efficiency ratios.

**NOTE: My code may include errors and *definitely* doesn't follow pythonic design patterns. None the less, if you find any errors or have any suggestions, please feel free to reach out to me via linkedin. Thanks!**